Implemetation of Ajax on vote boxes
pgaspar/oqfc pull request #2
Opened 2016-09-14 16:05 UTC by SnifeiNaSeven

Applied Ajax on the vote boxes and  made them disabled after voting.
Added new Route to get vote score.

2016-09-18 00:23 UTC, pgaspar commented on public/js/ajax.js
> +    })
This is pretty cool! However, there's one thing here that I would like you to address before merging the changes:

I see here that you are posting to `/vote` and then querying `/<id>/vote_score` to know the score you need to display. What people usually do in these cases is have the `/vote` action return the vote score. This way, you would just post to `/vote` and read whatever that action returned as the vote score. You can use `if request.xhr?` inside `post '/vote'` in `app.rb` to check if a request is AJAX.

So you could do something like:

```ruby
post '/vote' do
  entry = Entry.get!(params[:entry_id]) rescue halt(404)
  entry.vote(request.ip, params[:up] != 'false')

  if request.xhr?
    @entry[:vote_score].to_s
  elsif params[:vote_page]
    redirect to "/entry/#{entry.id}"
  else
    redirect to "/#suggestion-#{entry.id}"
  end
end
```

2016-09-18 00:41 UTC, pgaspar commented on public/js/ajax.js
> +    })
Update: Actually, we can do better than this.

Here is the issue with the approach above: whenever you vote, the span with id `vote_score` is updated to the new vote score. However, we are not updating the title attribute of that span. So if it said "Baseado em 3 votos." before you voted it will still say "3 votos" after you vote, instead of "4 votos".

And that's not the only thing: the up and down buttons also have a title attribute for when the user has already voted. It reads "Obrigado pelo teu voto!". Your javascript doesn't add this - it only makes the buttons disabled.

These two things are not super important, obviously, but we may just do it right, if we're taking the time. 

So, to deal with these issues, we can do things a bit differently: instead of having the `/vote` action return the score, like above, we can have it render the entire `views/_vote_box.erb` partial. This way we can just replace the whole thing and it will be perfectly rendered, with all the title attributes we need and the new vote score.

Here's how it could look like (I'm not 100% sure this syntax is accurate and I didn't test it myself):

```ruby
post '/vote' do
  entry = Entry.get!(params[:entry_id]) rescue halt(404)
  entry.vote(request.ip, params[:up] != 'false')

  if request.xhr?
    render :vote_box
  elsif params[:vote_page]
    redirect to "/entry/#{entry.id}"
  else
    redirect to "/#suggestion-#{entry.id}"
  end
end
```

You may need to change the `_vote_box.erb` partial just so everything it currently has gets put inside a div or a span. That way, in the javascript you can simply replace the contents of that div with whatever comes from the `/vote` action.

2016-09-18 00:43 UTC, pgaspar requested changes
This is great! Thanks for taking the time.
I suggest a few improvements to get this to perfection. 

Let me know if you need further help! Thanks.

2016-09-22 01:31 UTC, SnifeiNaSeven commented on public/js/ajax.js
> +    })
The render method(?) does not exist in sinatra.
We cant render the vote_box in the POST request, I have tried it (And it makes sense, at least in my idea of what a POST request is). The POST in this case is used to update the DB, right?

So to solve this issues we can make a GET request (like in the example), giving us a updated rendered vote_box. And with some javascript magic we can replace the targeted vote_box with the updated one.

```
get '/vote/:id' do
    @entry = Entry.get!(params[:id])  rescue halt(404)
    erb :vote_box , layout: false
end

post '/vote' do
  entry = Entry.get!(params[:entry_id]) rescue halt(404)
  entry.vote(request.ip, params[:up] != 'false')
  
  #If we are using ajax this is useless, right?
  if params[:vote_page]
    redirect to "/entry/#{entry.id}"
  else
    redirect to "/#suggestion-#{entry.id}"
  end
end
```

I needed to create a copy of _vote_box.erb named vote_box.erb because I couldnt render the _vote_box.erb, is it because it is a partial? In that case i would need the partial() method but i changed the code inside the vote_box.erb, instead of entry I used @entry.

```
<!--Changed for Ajax implementation-->
<span id="vote_score_<%= @entry.id %>" title="Baseado em <%= @entry.vote_count %> voto<%= 's' if @entry.vote_count != 1 %>." ><%= @entry.vote_score %></span><br/>
<div class="btn-group" value="<%= @entry.id %>">
    <button id="bt-up" value="true" class="btn btn-mini <%# 'btn-success' if @entry.voted_up?(request.ip) %>" <%= 'disabled title="Obrigado pelo teu voto!"' if @entry.already_voted?(request.ip) %> ><i class="icon-caret-up"></i></button>
    <button id="bt-dw" value="false" class="btn btn-mini <%# 'btn-danger' if @entry.voted_down?(request.ip) %>" <%= 'disabled title="Obrigado pelo teu voto!"' if @entry.already_voted?(request.ip) %> ><i class="icon-caret-down"></i></button>
</div>
```

And I changed the Ajax to simply

 ```
$(document).ready(function() {
    $("#bt-dw,#bt-up").click(function (event) {
        event.preventDefault();
        const id =  $(this).parent().attr("value");
        const up = $(this).attr("value");
        const curr = $(this);
        
        $.post("/vote?entry_id=" + id + "&up=" + up, function(){
                $.get("/vote/" + id, function(data){
                    console.log(data);
                    $("#suggestion-" + id + " .suggestion-votes").html(data);
                })
        })
    })
})
```

because the new vote_box comes with the buttons disabled, i think ...

2016-10-01 23:35 UTC, pgaspar commented on public/js/ajax.js
> +    })
> The render method(?) does not exist in sinatra.

Check [this entry](http://www.sinatrarb.com/faq.html#partials) in their FAQ. Also, I'm ok with us including a separate gem for this, if necessary.

> We cant render the vote_box in the POST request, I have tried it (And it makes sense, at least in my idea of what a POST request is). The POST in this case is used to update the DB, right?

While it's true that POST requests update the DB, they also send something in response.

Looking at Rails for guidance here, what happens there is that if the browser requests the HTML format, if the POST is successful, we actually redirect the user to the newly created object. If the format is XML or JSON, we actually send back an XML or JSON representation of the new object.
If the format is javascript (meaning, AJAX) Rails will actually render a Javascript partial and send that back as a response. So it basically sends back Javascript that is then executed on the client's browser. This javascript will usually include the new object rendered from an HTML partial.

Here's a Stack Overflow answer that sheds some light into the difference between HTML & XML/JSON requests: http://stackoverflow.com/a/11131630/2611145

For more info on how Ajax works on Rails (especially chapter 4): http://guides.rubyonrails.org/working_with_javascript_in_rails.html#server-side-concerns

(This is all to say that POST requests send back various types of responses, depending on the requested format).

> So to solve this issues we can make a GET request (like in the example), giving us a updated rendered vote_box.

I really don't like this, regardless of what we can or cannot do with partial rendering on Sinatra. The POST request should send the necessary info in its response so that the client can update the views. I don't like the idea of having to make a second request to get the updated vote box. It's even worse for the user, because it will not be as seamless as it should be (2 requests instead of 1).

> And I changed the Ajax to simply...

This looks good. Except there should be no `$.get` call, and `data` should come from the POST.

---

I can try playing with this soon as well and see what I can improve! Thanks once again!

2016-10-02 16:24 UTC, SnifeiNaSeven commented
OK so i removed the unnecessary get request and fixed the vote page cases that weren't previously covered.
And the POST request response was given by rendering a partial as you suggested.
Btw good call, makes the code far cleaner.

2016-10-02 18:48 UTC, pgaspar requested changes
This is much better! We're almost there. Left a few comments for you to address. This is the home stretch - thank you!

2016-10-02 18:48 UTC, pgaspar commented on app.rb
> +  @entry = Entry.create(text: EscapeUtils.escape_html(params[:suggestion]))
I believe this change is not needed (and actually makes this action raise an exception).

2016-10-02 18:48 UTC, pgaspar commented on public/js/ajax.js
> + $(document).ready(function() {
We use `jQuery(function ($) {` in the `default.js` file. Can we use it here too, to make it coherent?

2016-10-02 18:48 UTC, pgaspar commented on public/js/ajax.js
> +    $("#bt-dw,#bt-up").click(function (event) {
So, this project has a configuration (`block_repeated_votes` in `config.rb`) that when disabled will allow people to vote multiple times in the same entry. If you set it to false as a test and try to vote twice in the same entry you'll notice the second click won't work.

You can see the reason for this [here](http://stackoverflow.com/a/13767985/2611145).

I suggest you try something like this:

```javascript
$(document).on("click", "#bt-dw, #bt-up", function(event) {
```

2016-10-02 18:48 UTC, pgaspar commented on public/js/ajax.js
> +        let ext = $("<div></div>");
Lines 9, 12 and 13 should be removed as they are debug logs.
The `curr` variable is also never used.

2016-10-02 18:48 UTC, pgaspar commented on public/js/ajax.js
> +        const id =  $(this).parent().attr("value");
There are some things I would change in the way we get `vote_page` and `id`:

Using `parent()` like you're using here is brittle code - what I mean is that, if for some reason someone adds a span or a div between the `this` element and the element that has the `value` attribute, this code will no longer work. A better solution is to have something like `const vote_page = $(this).closest(".suggestion-votes").attr("value")`. This works because in both cases (vote page & not vote page) the value attribute is in an element with the `.suggestion-votes` class. We could even argue that it would be better to give those two elements a specific ID, so that this isn't dependent on presentation logic (classes are usually considered presentation logic).
For the `id` constant, `const id = $(this).closest(".btn-group").attr("value")` seems to work.

The other thing that I would improve here is the way you're using `.attr("value")`. What you're doing now is setting a `value` attribute on some elements to mean different things. Here's a better way:

For `vote_page`:
```html
<!-- _entry.erb -->
<td class="suggestion-votes">

<!-- entry.erb -->
<div id="entry-votes" class="suggestion-votes" data-vote-page="true">

<!-- ajax.js -->
const vote_page = $(this).closest(".suggestion-votes").data("vote-page");
```

For `id`:
```html
<!-- _vote_box.erb -->
<div class="btn-group" data-entry-id="<%= entry.id %>">

<!-- ajax.js -->
const id = $(this).closest(".btn-group").data("entry-id");
```

One cool thing about this way of doing things is that `vote_count` will actually have `true` or `false` instead of `"true"` or `"false"`. This will let us do `if (vote_page) {` in `ajax.js`.

2016-10-02 18:48 UTC, pgaspar commented on public/js/ajax.js
> +        $.post("/vote","entry_id=" + id + "&up=" + up,function(response){
jQuery's `$.post` function can actually take a JSON dictionary as the second argument, letting us do this instead:

```javascript
$.post("/vote", { entry_id: id, up: up }, function(response){
```

2016-10-02 18:48 UTC, pgaspar commented on public/js/ajax.js
> +            if(vote_page=="false") {
Here you can simply do `if (vote_page) {`, if you're using the `data-vote-page` pattern I suggested above.

2016-10-02 18:48 UTC, pgaspar commented on public/js/ajax.js
> +})
Indentation is funky in this file. We've been using 2-space indents in other JS files.

2016-10-02 22:49 UTC, SnifeiNaSeven commented on app.rb
> +  @entry = Entry.create(text: EscapeUtils.escape_html(params[:suggestion]))
It was a mistake, probably changed it thinking it was the post vote routeWa

2016-10-02 22:49 UTC, SnifeiNaSeven commented on public/js/ajax.js
> + $(document).ready(function() {
Makes sense

2016-10-02 22:49 UTC, SnifeiNaSeven commented on public/js/ajax.js
> +        const id =  $(this).parent().attr("value");
Didn't know closest method exist and the new propriety makes code easier to catch up with in the future, pretty cool

2016-10-02 22:49 UTC, SnifeiNaSeven commented on public/js/ajax.js
> +        let ext = $("<div></div>");
Yeah is trash from previous work.

2016-10-02 22:49 UTC, SnifeiNaSeven commented on public/js/ajax.js
> +        $.post("/vote","entry_id=" + id + "&up=" + up,function(response){
ok seems cleaner

2016-10-02 22:50 UTC, SnifeiNaSeven commented
Updated code based on suggestions

2016-10-03 00:12 UTC, pgaspar approved these changes

2016-10-03 00:13 UTC, pgaspar commented
This is great! Thank you 👍 I'll try getting this deployed soon.
Fixes #2.

2016-10-03 00:13 UTC, merged